name: Deploy Rspress site to Pages

on:
  push:
    branches: [main] # 监听 main 分支的推送
  workflow_dispatch: # 允许手动触发

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v3
        with:
          version: 10
          cache: pnpm

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: lint code
        run: pnpm lint

      - name: Build with rsbuild
        run: pnpm build
        env:
          - LIRY_ASSET_PREFIX: '/zzo/'

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist # next 生成的静态文件目录

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
